### ISSUE TITLE
Module Descriptions are being added as blank or strange pages (MATH 221B) - Check MATH 221B Week 01 "Course Introduction"

### ISSUE THREAD

**Issue by danverde** [byuitechops/remove-descriptions#1]

**Comment by sethchilders92** [comment]
Action-series-master universal-naming-conventions is adding the prefix to the odd headers. 

It looks like like SubModules in D2L are being converted over into pages instead of into SubHeaders, likely because the SubModules have descriptions of some sort. I will have to go into not only the module, but the SubModules and apply this child module to them. 

universal-naming-conventions doesn't rename SubHeaders, so once the descriptions are gone and they are converted to SubHeaders instead of pages, their naming convention should be correct.

**Comment by sethchilders92** [comment]
Ready for review @danverde

**Comment by zachintosh** [comment]
I'm not seeing this issue anymore.
